sudo: required
language: java
jdk:
- openjdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

deploy:
- provider: script
  script: ./gradlew build,./gradlew bintrayUpload
  skip_cleanup: true
  edge: true
  on:
    tags: true
    repo: hmcts/ccd-case-document-am-client
- provider: releases
  api_key:
    secure: Nbar+vfWYfsJnsbvAWAucAwN1fAVjzfnfggxp+0Mgo7ftpdGrhb/q7YHA6DYFjgGEC7HDCWwXHXfMVmKy8eaEqL/0fl5zxCcCEUuw73VxTh1XttTWZ5/IGcAdJcfttjbxMkwsWgRQUYg/NeZq8yHg/XmAvFkKPM/HXhvP4xGewW9ZZgk+Y/pm6D91kgnIKTDbIo8Z4vU/AJuAQggOU6MIRXNsmMiM/b2m0vlDpHO1SF+SQQXVsjJR/gh/IYL5xk8PCNUG6Tofsnlc1Zry9/YimP5NZROhnAZbh/sXPK7uefdkMkD7mVwXU9Ld+4LxEQ3pBb394zuDt4qGM45DntmdeaGFtbe874ypL7ONDeo/9wYZtUbpfpSPeJNmqkVgKAWSUsc7/OYb9W+kcYP2gf1SWn3mDJkP6MPct20GxvlHusr//pB5wvwOcZFvYkEZbwJ98ZGdbwsgTccKRpIp4XeN9eUGuY2Lf9eFMzbI6KmKSqp145PQwW99FQqmQqRPOMjZo4jS6G9NkR1YTQa1nEdwBFupaccEf77wTbpw4xCzEkZEJkLNoe2A4KbAg6CaNpBD3J91hRm9OcBVb4P7+7ReeJ+347SEZJcbyRODdG6865IcAZcgXyQIQlw/o45PbNYL4kHsGwNaSWC5UCs1BWwQ0f7jgH1OKXjJBtJ04AuAVU=
  file_glob: true
  edge: true
  file: build/libs/ccd-case-document-am-client-*.jar
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: E9hqxenq8Xz/GFPZWwz6vuXNSNwkyZsnjlnJTAYouh3AnRBZcHZueS2oslSUPQisOrCEz6K1QS4hjp0qlE+01MeW/1dsrx5YdJe8L5ZcDeJSZL6CLSEl56hss500NKUnT3lVYLOFXVjNUxv245TMfiuw8R4x8NHjJjFj65/CL7zxQ2rF29KS5PoH86dnKRiyzKGSWKV4LQoqaoEBj2H4BBQK1TQGhJC4nL9WCoGL0rNhv/jKnQBf1LtZd+fF+MlYcUn+btocVPV7ybJfjGyDGjreAqgHhyA/NDLcmXi6P1Uzruq/ODjw5YIJbZsch0mxlMGk2I+UFh7k/Mw2JEd7PYNaundws9sGW5JdUmIN4kWTDMq8WHoeW2Znf8vrkW3Xl+uU3JJE78V4Xw+l4NgHMiqjSRdlQL+eFPF7JajP4TaIG/Zx4iP91SuqbtQZw4O8e9g+93MjfG0CITfVTaaYPCp/cX7SH8hTd6haAI8Pwk0yC+EpJpjuR2nAGSnK8jGNa/6NBA2rgmf7Hb1dKfhf6cIYsjJE4kchs7f+kfBxuFmiggGWRYLt7Wkpvl8UR34BtWcd7L/SjuKpGNHbPZOKBk9Mgm3kNs9s+wo0lnLpzN2JFYAJUPhtzJqDR3RZAPlGf1/Wo9PrxtYc2VfnD+5pzMazLJe+w1cJMP8IstXnLhA=
  - secure: cdZVanqoE6tKvGn2QmOJ0K6BJBAva3PJdn/itt6pZ+eleVe3XpmhfGcMvE1NNLC3M6UP3fpJBmKxvJY4CMmJ66bPEHURO0n07+8gZj7gfgKkbYTcL4iNQEXoL9jC7grjBYDPu3VvXat22iEgyMhRI44GuUi6T0uvCHdgXWnvCCY7CYGOKTHulnZbw2j+ICXWifOJPjICLCX7SR6lcYYWNI7azj8JzNnQCSUmynlTtQWFYgoSi6KEGb/R25twXXqkhyTRxQsy5kpaqleOorVOO48z05gnZm106Q1AJdC3NmxbjYCfFUZeTR/uDqt8Gn36KaHpUiVhdcGUCNfwg1Z8BmxG6eoOFeAnOrd84i8cQyoPAVlD4rRTmjg+ha15khSiD+vXSatd2JIuhWZzQpyAuOSw76sUJGCvPtpSEXlReDwVK6sIvej1VCtZ42m0+J0Il4b2HBeFgi6vCDNFuatFYVEm60i+pMMiETXQeSIK0qsRFwPDlx+GtJvb6zlphc7MxKqr9d+zj6Syz5qQWYNfK2j/kum1BamZU0bHzPehrwCuUh0vx09L9KxBdW7ZR9Zk7x+Bd4CbZ7GBGd4hKp3flBTwS+/rU0sdpdCPo8WaBFf0OK2GuGiu+aymD5LGyUd0FwH0QARnh7ThkkHMCGB5Hc4xIiP7Lnf0SW4qk5h/RTM=
